# Generated by Django 5.0.3 on 2024-04-24 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfinput', '0003_alter_book_options_alter_bookinstance_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
