# Generated by Django 5.0.3 on 2024-04-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfinput', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
